### ISSUE TITLE
new version of Chrome and Edge

### ISSUE THREAD

**Issue by amirhosseinfaraji** [pagedjs/pagedjs#84]
Hi. I use paged js in my project and it was working fine. but after update chrome paged js not working well like before and I have `Unable to layout item: {nodeName}` warning in console. I use new version of paged js but again I had the issue. I tested on Opera browser and it work fine but on Chrome and Edge it dosen't work. Can you help me ? thanks.

**Comment by julientaq** [comment]
@amirhosseinfaraji that’s really weird. Could you share your html/css ? what version of chrome are you using?

**Comment by amirhosseinfaraji** [comment]
@julientaq thanks.
in our project we print employees cv and we work with Angular. but this sample I simulated our logic for printing cv. 
I tested on `Opera v87.0.4390.45` and `Chrome v102.0.5005.63`
please run my sample project with Live-server. 

[sample.zip](https://github.com/pagedjs/pagedjs/files/8863413/sample.zip)

**Comment by julientaq** [comment]
ok so, i checked and i dont see the error.
BUT i don’t have the images.

When an element is too big for the page, pagedjs creates a new page and tries to render it again. If there is still no room, it stops and console.log(unable to layout item).

So it can be a lot of things, from too big images to display grid here and there. 

Could you send me a the images to try and reproduce it?

I don’t think we tried with Opera yet, i need to look a bit that, if it works.

Thanks!

**Comment by amirhosseinfaraji** [comment]
@julientaq 
actually I tested a lot and I removed all images but the issue it didn't resolve. we just render some plain text. 
it's strange because today I tested on Chrome `v96` and it was working fine.  
I'm going to check step by step our project again and if I find solution for resolving the issue I inform.
Thanks a lot

**Comment by julientaq** [comment]
let me check my version of chrome again

**Comment by julientaq** [comment]
so yeah, updated on the latest, no issue here. 
What OS are you using?

**Comment by amirhosseinfaraji** [comment]
@julientaq we have this issue on windows 10 , 11 and macOs

**Comment by eduarevalo** [comment]
@julientaq I think this issue deserves some attention. I had a kind of similar issue some days ago while testing from my mac with chrome `Version 102.0.5005.61 (Official Build) (x86_64)`. I can't really provide more details right now.

**Comment by julientaq** [comment]
Absolutely agree, and yet i can’t  reproduce the issue with chromium 104.0.5110.0

**Comment by janmohammadi** [comment]
Hi everyone,
Just some more information about the issue:
We implemented this features about year ago and it was working properly until a while ago, and we had no updates on this feature. So the only thing has changed here is the Chrome version.
It puts a page break and then removes some data from the page. I've attached the expected and actual printed pages as PDF.
Also the console log is attached.
[normal.pdf](https://github.com/pagedjs/pagedjs/files/8873070/normal.pdf)
[wrong.pdf](https://github.com/pagedjs/pagedjs/files/8873071/wrong.pdf)
[localhost-1654800091785.log](https://github.com/pagedjs/pagedjs/files/8873072/localhost-1654800091785.log)

I've tested this on, Windows (10,11) - Chrome 102.0.5005.63

Kind Regards,
Reza

**Comment by julientaq** [comment]
@janmohammadi do you have the html + css + js?

there is some trickery in this.
Does that happens on chromium too for yall?

**Comment by janmohammadi** [comment]
Some more information:

I found that Chrome had some changes on @page media query in version 102 which is close to the date that we faced the issue.
I checked the change log and I found that there are some changes related to the media queries and @page. But TBH I couldn't undrestand what are the acutal changes. 

![image](https://user-images.githubusercontent.com/4748657/172929837-c7ad9825-6d27-4edd-b957-17997870b0f8.png)
https://chromereleases.googleblog.com/2022/05/stable-channel-update-for-desktop_24.html
https://chromium.googlesource.com/chromium/src/+log/101.0.4951.67..102.0.5005.63?pretty=fuller&n=10000

**Comment by julientaq** [comment]
thanks! gonna dig it!

**Comment by julientaq** [comment]
Ok so this is weird.
That said, the @page size only affect the output when you hit the print button. But not the preview on screen, so there is something else.
I would assume an issue with the column (pagedjs uses column to find pagebreak

The other weird thing: if we remove the  css, it still doesnt work, so we looked deeper.

If we replace the custom elements with a div, it works fine 

Could you try adding a display block to the custom elements? 
Custom element with paged.js have always been problematic.  What’s weird though, is that you say that it worked before 🤔

**Comment by eduarevalo** [comment]
> Could you try adding a display block to the custom elements?

@amirhosseinfaraji @janmohammadi Have this hint fixed your issue on v102?

**Comment by janmohammadi** [comment]
The both ways works. I replaced those custom elements with div tags and I also tried disply:block in css.
I'll pick the the first one as it looks more stable solution.
Thank you so much! :)

**Comment by julientaq** [comment]
Your welcome!, did it work in previous version of chrome (before 102) ?

**Comment by janmohammadi** [comment]
@amirhosseinfaraji  could you please also test it on the older versions (maybe also other browsers)?

**Comment by amirhosseinfaraji** [comment]
@julientaq  , @janmohammadi 

I tested on Chrome `v101.0.4951.67` , Edge `v102.0.1245.39` , Opera `v87.0.4390.45` also Opera `v88.0.4412.27` 
they worked fine.

**Comment by carstenschwede** [comment]
I have a similar issue when the TOC as generated using the script from https://gitlab.coko.foundation/pagedjs/experiments/tree/master/table-of-content is longer than one page.

**Comment by imkaty** [comment]
My table of contents, which spans multiple pages, no longer spans multiple pages on Edge or Chrome. The table of contents gets bumped to the second page, leaving what should have been the TOC first page blank, and the the visible TOC is only visible on that second page. The content of the book starts on the third page instead of being bumped down to the 4th or 5th, depending on how long the TOC is.

It does work just as expected on Opera, however. 

**Versions:**
Edge: Version 103.0.1264.44 (Official build) (64-bit)
Chrome: Version 103.0.5060.114 (Official Build) (64-bit)
Opera: 88.0.4412.53

**Comment by janmohammadi** [comment]
Hi there,

@imkaty could you please share some examples from the page?

**Comment by imkaty** [comment]
Thanks, @janmohammadi. Here are 2 PDFs saved from HTML that demonstrate the differences in how the TOC is showing up:
Edge-generated version:
[ChecklistSampleEdge.pdf](https://github.com/pagedjs/pagedjs/files/9049188/ChecklistSampleEdge.pdf)
Opera-generated version:
[ChecklistSampleOpera.pdf](https://github.com/pagedjs/pagedjs/files/9049190/ChecklistSampleOpera.pdf)

**Comment by liamsmithaha** [comment]
same issue, whole environments broke without code change, and opera works, firefox worked for a bit then must of run an update then broke, paged is incompatible with this version of CSS page media, i pray the issue isn't hard to patch.

**Comment by carstenschwede** [comment]
@imkaty: Can you a) provide the HTML that caused this and b) try removing the `@page tableofcontent {}` CSS rule if you have a named your TOC page?

**Comment by imkaty** [comment]
I'm not 100% on the best thing to send you for code, but here is a stab. Everything on the webpage works fine except the table of contents, but the TOC is necessary to have. 

I used the code from here as my base to build my TOC:
([(https://gitlab.coko.foundation/pagedjs/experiments/-/tree/master/table-of-content)])

**JS:**
Note that in **createToc.js**, I did change line 58 as I had some really long chapter headings that buggered up the leaders in the TOC:
_**Original:**_
`tocNewLi.innerHTML = '<a href="#' + tocElement.id + '">' + tocElement.innerHTML + '</a>';`

_**Mine:**_
`tocNewLi.innerHTML = '<a href="#' + tocElement.id + '"><span class="toc-title-span">' + tocElement.innerHTML + '<span class="leader-dots"></span></span></a>';`

**CSS:**
Here is my CSS, some of which overrides table-of-content.css from your code:
[printstyles.css.txt](https://github.com/pagedjs/pagedjs/files/9067908/printstyles.css.txt)

     
**HTML**
Here is my TOC HTML:
```
<section id="table-of-contents">
    <h2 class="mb-3">Contents</h2>
    <nav id="my-toc-content">
    </nav>
</section>
```

Hope that is helpful, tell me if more needed.

**Comment by julientaq** [comment]
So yeah, as we said in #89, chromium update and their new LayoutNG kind of put us back to the drawing board. We need to get the right strategy to get away with this.

Meatime, if your toc is set using flex, please remove it and tell us if it’s better.

**Comment by imkaty** [comment]
Alas, it is now broken in Opera too, in the same way as Chrome and Edge.

**Comment by imkaty** [comment]
BTW, doing this in your table-of-content.css did not fix or change the problem:

```
#list-toc-generated .toc-element {
            /*display: flex;*/
        }
```

**Comment by julientaq** [comment]
oh interresting. 

we need to check that out, thanks!

**Comment by imkaty** [comment]
> > Thanks, @janmohammadi. Here are 2 PDFs saved from HTML that demonstrate the differences in how the TOC is showing up: Edge-generated version: [ChecklistSampleEdge.pdf](https://github.com/pagedjs/pagedjs/files/9049188/ChecklistSampleEdge.pdf) Opera-generated version: [ChecklistSampleOpera.pdf](https://github.com/pagedjs/pagedjs/files/9049190/ChecklistSampleOpera.pdf)
> 
> We had the same issue in our reports. I was able to resolve the issue by changing `overflow-x: hidden` to `overflow-x: clip;` on the `#list-toc-generated` style

Hurray, that works for me!! Many thanks. @ldy985

**Comment by machal** [comment]
So i there list of recommendations to solve `Unable to layout` issue? I'm seeing lot of partial solutions here, but nothing works for me.

I have the same one, using Chrome 104. Tried in Canary 107 too, which is a little bit better, but does not render everything in HTML too.

I have tried to:

- change CSS as been written here
- remove all CSS
- update to Paged.js v0.4.0-beta.1

Nothing is helping me.

Four months ago I had the same issue with `Unable to layout` on `h1` element. I solved it in this commit:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/16641/185736867-685b07e2-d533-4b4d-babd-ef7d29ff30e8.png">

Maybe it can be useful for your debugging.

But now it is different… Nothing is solving the issue.

**Comment by machal** [comment]
It looks I solved the issue with `Unable to layout item` by installing older version of Chrome, particulary version 99:

1. I have read [this Stack Overflow question](https://stackoverflow.com/questions/3785991/can-i-run-multiple-versions-of-google-chrome-on-the-same-machine-mac-or-window). 
2. I'm using Mac, so I followed [these steps](https://stackoverflow.com/a/19672729/889682).
3. You should change the `google-chrome-version-start.sh` script. My version looks like this:

```shell
#!/usr/bin/env bash
/Applications/Google\ Chrome\ 99.app/Contents/MacOS/Google\ Chrome --user-data-dir="tmp/Google Chrome/99/" & disown
```

No I'm able to run two version of Chrome…

<img width="172" alt="image" src="https://user-images.githubusercontent.com/16641/186844517-60adfad7-55f4-4bca-8d3f-1499a5650957.png">

… and in the version of 99 there is no problem with Paged.js.

This is hotfix, but I'm my solution helps to someone.

**Comment by julientaq** [comment]
@machal Unable for layout can come from so many different places.

However it means that an element is bigger than your page, and that there isn’t enough room for the element. 
This can happen when an image is larger or higher than the page. Sometimes, 1px is enough to break everything.
 
About your issue 4 months ago, it’s hard to see how this css change fixed the “unable to layout”. It shouldn’t be an issue. You may have find something there. I guess you can’t reproduce the bug and the fix you had at the time, can you?  

If you want to share the html / css that break, that would help us to see what happens.

**Comment by machal** [comment]
@julientaq Thanks for writing.

> it means that an element is bigger than your page … Sometimes, 1px is enough to break everything.

This is great information for me to debug those issue.

For now, I'm able to solve it with older version of Chrome as I mentioned in [latest comment](https://github.com/pagedjs/pagedjs/issues/84#issuecomment-1228140216).

I've got these issues in 440 pages book, so sharing CSS and HTML is not so easy. I will try to isolate issues and share the HTML/CSS for you later.

**Comment by cderv** [comment]
We encountered also the issue on a doc with a long TOC that needs to break on two pages. 

Our default css we used had this:
````css
.toc ul, .lot ul, .lof ul {
  list-style: none;
  padding-left: 0;
  overflow-x: hidden;
}
````

by following answer above https://github.com/pagedjs/pagedjs/issues/84#issuecomment-1219203532 changing to `overflow-x: clip;` solved it. 

So it seems the `overflow-x: hidden` rule was the culprit. 

@julientaq I am not sure to know where to look in paged.js to debug this based on the information. I can try make a reproducible example - I just need to make one without the help of **pagedown**, our R wrapper to use paged.js in documents. 
Happy to set some time with you live, if that can help. 

I'll go for the workaround for now.

**Comment by julientaq** [comment]
yeah that ’s what we’re looking at.

@cderv have you tried the latest 0.4.0b? 

I’m curious to know if that helps on your  end

**Comment by cderv** [comment]
No I did not. i'll see if I can easily update without any change to our custom hooks. Thanks for pointing that out.

**Comment by julientaq** [comment]
Read the article on the blod, it comes with changes.
